# Generated by Django 5.0.1 on 2024-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
