# Generated by Django 5.0.1 on 2024-01-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artwork', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('character', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
