# Generated by Django 5.0.1 on 2024-01-12 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_comic_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='favourites',
            field=models.ManyToManyField(related_name='comics_fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
