# Generated by Django 5.0.1 on 2024-01-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comic_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='author',
        ),
    ]
