# Generated by Django 5.0.1 on 2024-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('comics', '0004_remove_comic_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='authors',
            field=models.ManyToManyField(related_name='comics', to='authors.author'),
        ),
    ]
