# Generated by Django 5.0.1 on 2024-01-12 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_remove_comic_character_comic_characters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='comics_fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
