# Generated by Django 5.0.1 on 2024-01-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_alter_comic_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
